server:
  port: 7555
spring:
  application:
    name: hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://138.128.194.71:7777/eureka/
  instance:
    hostname:feign
ribbon:
  eureka:
    enabled: true
  service-login:
    ribbon: com.netflix.loadbalancer.RandomRule